# Generated by Django 5.2.5 on 2025-09-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_news_store_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khuyến mãi')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Phần trăm giảm giá')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='products.product')),
            ],
            options={
                'verbose_name': 'Khuyến mãi',
                'verbose_name_plural': 'Khuyến mãi',
            },
        ),
    ]
