# Generated by Django 5.2.5 on 2025-09-10 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh sản phẩm (chính)'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/extra/', verbose_name='Ảnh phụ')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Mô tả ảnh')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Ảnh sản phẩm phụ',
                'verbose_name_plural': 'Ảnh sản phẩm phụ',
            },
        ),
    ]
