# Generated by Django 5.2.5 on 2025-09-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_flash_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_promotion',
        ),
        migrations.AddField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='Sản phẩm hot'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_flash_sale',
            field=models.BooleanField(default=False, verbose_name='Flash Sale'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_promotion',
            field=models.BooleanField(default=False, verbose_name='Khuyến mãi'),
        ),
    ]
