# Generated by Django 5.2.5 on 2025-09-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_is_flash_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_flash_sale',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_promotion',
        ),
        migrations.AddField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False, verbose_name='Flash Sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_promotion',
            field=models.BooleanField(default=False, verbose_name='Khuyến mãi'),
        ),
    ]
