# Generated by Django 5.2.5 on 2025-09-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productimage_is_flash_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(blank=True, verbose_name='Cách dùng'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Thành phần'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.TextField(blank=True, verbose_name='Công dụng'),
        ),
    ]
