# Generated by Django 5.2.5 on 2025-09-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_how_to_use_product_ingredients_product_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Giá gốc của sản phẩm (nếu có)', max_digits=12, null=True, verbose_name='Giá gốc'),
        ),
    ]
