# Generated by Django 5.2.5 on 2025-09-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xuất xứ thương hiệu'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='Xuất xứ thương hiệu'),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Loại da'),
        ),
        migrations.AddField(
            model_name='product',
            name='texture',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kết cấu'),
        ),
    ]
