# Generated by Django 5.2.5 on 2025-09-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_category_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_gift',
            field=models.BooleanField(default=False, verbose_name='Có quà tặng'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày kết thúc Flash Sale'),
        ),
    ]
