# Generated by Django 5.2.5 on 2025-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_has_gift_product_sale_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='origin',
        ),
        migrations.AlterField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại da'),
        ),
        migrations.AlterField(
            model_name='product',
            name='texture',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kết cấu'),
        ),
    ]
