# Generated by Django 5.2.5 on 2025-09-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_origin_alter_product_is_flash_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDealBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tiêu đề banner')),
                ('image', models.ImageField(upload_to='hotdeals/', verbose_name='Ảnh banner Hot Deals')),
                ('link', models.URLField(blank=True, verbose_name='Liên kết khi click')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Hot Deal Banner',
                'verbose_name_plural': 'Hot Deal Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
