# Generated by Django 5.2.5 on 2025-09-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_hotdealbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('bank', 'Chuyển khoản ngân hàng'), ('momo', 'Ví MoMo'), ('vnpay', 'VNPay'), ('zalopay', 'ZaloPay'), ('credit', 'Thẻ tín dụng/Ghi nợ')], default='cod', max_length=20, verbose_name='Hình thức thanh toán'),
        ),
    ]
