# Generated by Django 5.2.5 on 2025-10-08 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_store_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True, verbose_name='Câu hỏi thường gặp')),
                ('answer', models.TextField(verbose_name='Câu trả lời')),
                ('tags', models.CharField(blank=True, help_text='Phân tách bởi dấu phẩy, ví dụ: son, môi, đỏ', max_length=255, verbose_name='Từ khóa liên quan')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Câu hỏi thường gặp (FAQ)',
                'verbose_name_plural': 'Câu hỏi thường gặp (FAQ)',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('message', models.TextField(verbose_name='Tin nhắn người dùng')),
                ('bot_reply', models.TextField(verbose_name='Phản hồi của bot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử chat chatbot',
                'verbose_name_plural': 'Lịch sử chat chatbot',
                'ordering': ['-created_at'],
            },
        ),
    ]
