# Generated by Django 5.2.5 on 2025-10-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_review_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_origin',
            field=models.TextField(blank=True, null=True, verbose_name='Xuất xứ thương hiệu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_type',
            field=models.TextField(blank=True, null=True, verbose_name='Loại da'),
        ),
        migrations.AlterField(
            model_name='product',
            name='texture',
            field=models.TextField(blank=True, null=True, verbose_name='Kết cấu'),
        ),
    ]
