# Generated by Django 5.2.5 on 2025-10-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_brand_origin_alter_product_skin_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.TextField(verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(verbose_name='Tên sản phẩm'),
        ),
    ]
