# Generated by Django 5.2.5 on 2025-10-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_orderitem_product_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.TextField(unique=True, verbose_name='Tên thương hiệu'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(unique=True, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.TextField(verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.TextField(verbose_name='Tên khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.TextField(verbose_name='Tên cửa hàng'),
        ),
    ]
