# Generated by Django 5.2.5 on 2025-10-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider/Banner', 'verbose_name_plural': 'Sliders/Banners'},
        ),
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị, có thể kéo thả trong admin'),
        ),
    ]
