# Generated by Django 5.2.5 on 2025-10-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_slider_options_slider_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Slider/Banner', 'verbose_name_plural': 'Sliders/Banners'},
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='order',
            new_name='sort_order',
        ),
    ]
