# Generated by Django 5.2.14 on 2026-05-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_slider_options_rename_order_slider_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Đã thanh toán'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã giao dịch'),
        ),
    ]
